// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// EntraEventIdentity represents the Identity of the object.
var EntraEventIdentity = elemental.Identity{
	Name:     "entraevent",
	Category: "entraevents",
	Package:  "a3s",
	Private:  false,
}

// EntraEventsList represents a list of EntraEvents
type EntraEventsList []*EntraEvent

// Identity returns the identity of the objects in the list.
func (o EntraEventsList) Identity() elemental.Identity {

	return EntraEventIdentity
}

// Copy returns a pointer to a copy the EntraEventsList.
func (o EntraEventsList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the EntraEventsList.
func (o EntraEventsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*EntraEvent))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o EntraEventsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o EntraEventsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the EntraEventsList converted to SparseEntraEventsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o EntraEventsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseEntraEventsList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseEntraEvent)
	}

	return out
}

// Version returns the version of the content.
func (o EntraEventsList) Version() int {

	return 1
}

// EntraEvent represents the model of a entraevent
type EntraEvent struct {
	// The raw content of the notification event.
	Payload string `json:"payload" msgpack:"payload" bson:"-" mapstructure:"payload,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewEntraEvent returns a new *EntraEvent
func NewEntraEvent() *EntraEvent {

	return &EntraEvent{
		ModelVersion: 1,
	}
}

// Identity returns the Identity of the object.
func (o *EntraEvent) Identity() elemental.Identity {

	return EntraEventIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *EntraEvent) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *EntraEvent) SetIdentifier(id string) {

}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *EntraEvent) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesEntraEvent{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *EntraEvent) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesEntraEvent{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *EntraEvent) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *EntraEvent) BleveType() string {

	return "entraevent"
}

// DefaultOrder returns the list of default ordering fields.
func (o *EntraEvent) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *EntraEvent) Doc() string {

	return `API to handle entra subscription events.`
}

func (o *EntraEvent) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *EntraEvent) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseEntraEvent{
			Payload: &o.Payload,
		}
	}

	sp := &SparseEntraEvent{}
	for _, f := range fields {
		switch f {
		case "payload":
			sp.Payload = &(o.Payload)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseEntraEvent to the object.
func (o *EntraEvent) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseEntraEvent)
	if so.Payload != nil {
		o.Payload = *so.Payload
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *EntraEvent) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *EntraEvent) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the EntraEvent.
func (o *EntraEvent) DeepCopy() *EntraEvent {

	if o == nil {
		return nil
	}

	out := &EntraEvent{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *EntraEvent.
func (o *EntraEvent) DeepCopyInto(out *EntraEvent) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy EntraEvent: %s", err))
	}

	*out = *target.(*EntraEvent)
}

// Validate valides the current information stored into the structure.
func (o *EntraEvent) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*EntraEvent) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := EntraEventAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return EntraEventLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*EntraEvent) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return EntraEventAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *EntraEvent) ValueForAttribute(name string) any {

	switch name {
	case "payload":
		return o.Payload
	}

	return nil
}

// EntraEventAttributesMap represents the map of attribute for EntraEvent.
var EntraEventAttributesMap = map[string]elemental.AttributeSpecification{
	"Payload": {
		AllowedChoices: []string{},
		ConvertedName:  "Payload",
		Description:    `The raw content of the notification event.`,
		Exposed:        true,
		Name:           "payload",
		Type:           "string",
	},
}

// EntraEventLowerCaseAttributesMap represents the map of attribute for EntraEvent.
var EntraEventLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"payload": {
		AllowedChoices: []string{},
		ConvertedName:  "Payload",
		Description:    `The raw content of the notification event.`,
		Exposed:        true,
		Name:           "payload",
		Type:           "string",
	},
}

// SparseEntraEventsList represents a list of SparseEntraEvents
type SparseEntraEventsList []*SparseEntraEvent

// Identity returns the identity of the objects in the list.
func (o SparseEntraEventsList) Identity() elemental.Identity {

	return EntraEventIdentity
}

// Copy returns a pointer to a copy the SparseEntraEventsList.
func (o SparseEntraEventsList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseEntraEventsList.
func (o SparseEntraEventsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseEntraEvent))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseEntraEventsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseEntraEventsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseEntraEventsList converted to EntraEventsList.
func (o SparseEntraEventsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseEntraEventsList) Version() int {

	return 1
}

// SparseEntraEvent represents the sparse version of a entraevent.
type SparseEntraEvent struct {
	// The raw content of the notification event.
	Payload *string `json:"payload,omitempty" msgpack:"payload,omitempty" bson:"-" mapstructure:"payload,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseEntraEvent returns a new  SparseEntraEvent.
func NewSparseEntraEvent() *SparseEntraEvent {
	return &SparseEntraEvent{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseEntraEvent) Identity() elemental.Identity {

	return EntraEventIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseEntraEvent) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseEntraEvent) SetIdentifier(id string) {

}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseEntraEvent) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseEntraEvent{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseEntraEvent) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseEntraEvent{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseEntraEvent) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseEntraEvent) ToPlain() elemental.PlainIdentifiable {

	out := NewEntraEvent()
	if o.Payload != nil {
		out.Payload = *o.Payload
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseEntraEvent) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseEntraEvent) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the SparseEntraEvent.
func (o *SparseEntraEvent) DeepCopy() *SparseEntraEvent {

	if o == nil {
		return nil
	}

	out := &SparseEntraEvent{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseEntraEvent.
func (o *SparseEntraEvent) DeepCopyInto(out *SparseEntraEvent) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseEntraEvent: %s", err))
	}

	*out = *target.(*SparseEntraEvent)
}

type mongoAttributesEntraEvent struct {
}
type mongoAttributesSparseEntraEvent struct {
}
