// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// IssueOAuth2 represents the model of a issueoauth2
type IssueOAuth2 struct {
	// Contains the auth URL is noAuthRedirect is set to true.
	AuthURL string `json:"authURL,omitempty" msgpack:"authURL,omitempty" bson:"-" mapstructure:"authURL,omitempty"`

	// OAuth code.
	Code string `json:"code" msgpack:"code" bson:"-" mapstructure:"code,omitempty"`

	// If set, instruct the server to return the OAuth2 auth url in authURL instead of
	// performing an HTTP redirection.
	NoAuthRedirect bool `json:"noAuthRedirect" msgpack:"noAuthRedirect" bson:"-" mapstructure:"noAuthRedirect,omitempty"`

	// OAuth2 redirect url in case of error.
	RedirectErrorURL string `json:"redirectErrorURL" msgpack:"redirectErrorURL" bson:"-" mapstructure:"redirectErrorURL,omitempty"`

	// OAuth2 redirect url.
	RedirectURL string `json:"redirectURL" msgpack:"redirectURL" bson:"-" mapstructure:"redirectURL,omitempty"`

	// OAuth state.
	State string `json:"state" msgpack:"state" bson:"-" mapstructure:"state,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewIssueOAuth2 returns a new *IssueOAuth2
func NewIssueOAuth2() *IssueOAuth2 {

	return &IssueOAuth2{
		ModelVersion: 1,
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *IssueOAuth2) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesIssueOAuth2{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *IssueOAuth2) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesIssueOAuth2{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// BleveType implements the bleve.Classifier Interface.
func (o *IssueOAuth2) BleveType() string {

	return "issueoauth2"
}

// DeepCopy returns a deep copy if the IssueOAuth2.
func (o *IssueOAuth2) DeepCopy() *IssueOAuth2 {

	if o == nil {
		return nil
	}

	out := &IssueOAuth2{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *IssueOAuth2.
func (o *IssueOAuth2) DeepCopyInto(out *IssueOAuth2) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy IssueOAuth2: %s", err))
	}

	*out = *target.(*IssueOAuth2)
}

// Validate valides the current information stored into the structure.
func (o *IssueOAuth2) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*IssueOAuth2) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := IssueOAuth2AttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return IssueOAuth2LowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*IssueOAuth2) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return IssueOAuth2AttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *IssueOAuth2) ValueForAttribute(name string) any {

	switch name {
	case "authURL":
		return o.AuthURL
	case "code":
		return o.Code
	case "noAuthRedirect":
		return o.NoAuthRedirect
	case "redirectErrorURL":
		return o.RedirectErrorURL
	case "redirectURL":
		return o.RedirectURL
	case "state":
		return o.State
	}

	return nil
}

// IssueOAuth2AttributesMap represents the map of attribute for IssueOAuth2.
var IssueOAuth2AttributesMap = map[string]elemental.AttributeSpecification{
	"AuthURL": {
		AllowedChoices: []string{},
		ConvertedName:  "AuthURL",
		Description:    `Contains the auth URL is noAuthRedirect is set to true.`,
		Exposed:        true,
		Name:           "authURL",
		ReadOnly:       true,
		Type:           "string",
	},
	"Code": {
		AllowedChoices: []string{},
		ConvertedName:  "Code",
		Description:    `OAuth code.`,
		Exposed:        true,
		Name:           "code",
		Type:           "string",
	},
	"NoAuthRedirect": {
		AllowedChoices: []string{},
		ConvertedName:  "NoAuthRedirect",
		Description: `If set, instruct the server to return the OAuth2 auth url in authURL instead of
performing an HTTP redirection.`,
		Exposed: true,
		Name:    "noAuthRedirect",
		Type:    "boolean",
	},
	"RedirectErrorURL": {
		AllowedChoices: []string{},
		ConvertedName:  "RedirectErrorURL",
		Description:    `OAuth2 redirect url in case of error.`,
		Exposed:        true,
		Name:           "redirectErrorURL",
		Type:           "string",
	},
	"RedirectURL": {
		AllowedChoices: []string{},
		ConvertedName:  "RedirectURL",
		Description:    `OAuth2 redirect url.`,
		Exposed:        true,
		Name:           "redirectURL",
		Type:           "string",
	},
	"State": {
		AllowedChoices: []string{},
		ConvertedName:  "State",
		Description:    `OAuth state.`,
		Exposed:        true,
		Name:           "state",
		Type:           "string",
	},
}

// IssueOAuth2LowerCaseAttributesMap represents the map of attribute for IssueOAuth2.
var IssueOAuth2LowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"authurl": {
		AllowedChoices: []string{},
		ConvertedName:  "AuthURL",
		Description:    `Contains the auth URL is noAuthRedirect is set to true.`,
		Exposed:        true,
		Name:           "authURL",
		ReadOnly:       true,
		Type:           "string",
	},
	"code": {
		AllowedChoices: []string{},
		ConvertedName:  "Code",
		Description:    `OAuth code.`,
		Exposed:        true,
		Name:           "code",
		Type:           "string",
	},
	"noauthredirect": {
		AllowedChoices: []string{},
		ConvertedName:  "NoAuthRedirect",
		Description: `If set, instruct the server to return the OAuth2 auth url in authURL instead of
performing an HTTP redirection.`,
		Exposed: true,
		Name:    "noAuthRedirect",
		Type:    "boolean",
	},
	"redirecterrorurl": {
		AllowedChoices: []string{},
		ConvertedName:  "RedirectErrorURL",
		Description:    `OAuth2 redirect url in case of error.`,
		Exposed:        true,
		Name:           "redirectErrorURL",
		Type:           "string",
	},
	"redirecturl": {
		AllowedChoices: []string{},
		ConvertedName:  "RedirectURL",
		Description:    `OAuth2 redirect url.`,
		Exposed:        true,
		Name:           "redirectURL",
		Type:           "string",
	},
	"state": {
		AllowedChoices: []string{},
		ConvertedName:  "State",
		Description:    `OAuth state.`,
		Exposed:        true,
		Name:           "state",
		Type:           "string",
	},
}

type mongoAttributesIssueOAuth2 struct {
}
