// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// IssueTokenExchange represents the model of a issuetokenexchange
type IssueTokenExchange struct {
	// The access token to validate with DSG auth.
	AccessToken string `json:"accessToken" msgpack:"accessToken" bson:"-" mapstructure:"accessToken,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewIssueTokenExchange returns a new *IssueTokenExchange
func NewIssueTokenExchange() *IssueTokenExchange {

	return &IssueTokenExchange{
		ModelVersion: 1,
	}
}
func (o *IssueTokenExchange) Identity() elemental.Identity {

	return elemental.Identity{}
}
func (o *IssueTokenExchange) Identifier() string {

	return ""
}
func (o *IssueTokenExchange) SetIdentifier(id string) {
	panic("you cannot set identifier on a detached object")
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *IssueTokenExchange) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesIssueTokenExchange{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *IssueTokenExchange) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesIssueTokenExchange{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *IssueTokenExchange) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *IssueTokenExchange) BleveType() string {

	return "issuetokenexchange"
}

// Doc returns the documentation for the object
func (o *IssueTokenExchange) Doc() string {

	return `Additional issuing information for DSG token exchange source.`
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *IssueTokenExchange) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *IssueTokenExchange) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the IssueTokenExchange.
func (o *IssueTokenExchange) DeepCopy() *IssueTokenExchange {

	if o == nil {
		return nil
	}

	out := &IssueTokenExchange{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *IssueTokenExchange.
func (o *IssueTokenExchange) DeepCopyInto(out *IssueTokenExchange) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy IssueTokenExchange: %s", err))
	}

	*out = *target.(*IssueTokenExchange)
}

// Validate valides the current information stored into the structure.
func (o *IssueTokenExchange) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("accessToken", o.AccessToken); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*IssueTokenExchange) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := IssueTokenExchangeAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return IssueTokenExchangeLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*IssueTokenExchange) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return IssueTokenExchangeAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *IssueTokenExchange) ValueForAttribute(name string) any {

	switch name {
	case "accessToken":
		return o.AccessToken
	}

	return nil
}

// IssueTokenExchangeAttributesMap represents the map of attribute for IssueTokenExchange.
var IssueTokenExchangeAttributesMap = map[string]elemental.AttributeSpecification{
	"AccessToken": {
		AllowedChoices: []string{},
		ConvertedName:  "AccessToken",
		Description:    `The access token to validate with DSG auth.`,
		Exposed:        true,
		Name:           "accessToken",
		Required:       true,
		Type:           "string",
	},
}

// IssueTokenExchangeLowerCaseAttributesMap represents the map of attribute for IssueTokenExchange.
var IssueTokenExchangeLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"accesstoken": {
		AllowedChoices: []string{},
		ConvertedName:  "AccessToken",
		Description:    `The access token to validate with DSG auth.`,
		Exposed:        true,
		Name:           "accessToken",
		Required:       true,
		Type:           "string",
	},
}

type mongoAttributesIssueTokenExchange struct {
}
