// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// NamespaceLifecycleIdentity represents the Identity of the object.
var NamespaceLifecycleIdentity = elemental.Identity{
	Name:     "namespacelifecycle",
	Category: "namespacelifecycles",
	Package:  "a3s",
	Private:  true,
}

// NamespaceLifecyclesList represents a list of NamespaceLifecycles
type NamespaceLifecyclesList []*NamespaceLifecycle

// Identity returns the identity of the objects in the list.
func (o NamespaceLifecyclesList) Identity() elemental.Identity {

	return NamespaceLifecycleIdentity
}

// Copy returns a pointer to a copy the NamespaceLifecyclesList.
func (o NamespaceLifecyclesList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the NamespaceLifecyclesList.
func (o NamespaceLifecyclesList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*NamespaceLifecycle))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o NamespaceLifecyclesList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o NamespaceLifecyclesList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the NamespaceLifecyclesList converted to SparseNamespaceLifecyclesList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o NamespaceLifecyclesList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseNamespaceLifecyclesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseNamespaceLifecycle)
	}

	return out
}

// Version returns the version of the content.
func (o NamespaceLifecyclesList) Version() int {

	return 1
}

// NamespaceLifecycle represents the model of a namespacelifecycle
type NamespaceLifecycle struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Bounded canonical lifecycle state owned by the namespace owner.
	Data string `json:"-" msgpack:"-" bson:"data" mapstructure:"-,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Immutable canonical name retained across deletion to forbid unsafe reuse.
	NamespaceName string `json:"-" msgpack:"-" bson:"namespacename" mapstructure:"-,omitempty"`

	// Monotonic conditional-write revision.
	Revision int `json:"-" msgpack:"-" bson:"revision" mapstructure:"-,omitempty"`

	// Hash of the object used to shard the data.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewNamespaceLifecycle returns a new *NamespaceLifecycle
func NewNamespaceLifecycle() *NamespaceLifecycle {

	return &NamespaceLifecycle{
		ModelVersion: 1,
	}
}

// Identity returns the Identity of the object.
func (o *NamespaceLifecycle) Identity() elemental.Identity {

	return NamespaceLifecycleIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *NamespaceLifecycle) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *NamespaceLifecycle) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *NamespaceLifecycle) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesNamespaceLifecycle{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.Data = o.Data
	s.Namespace = o.Namespace
	s.NamespaceName = o.NamespaceName
	s.Revision = o.Revision
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *NamespaceLifecycle) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesNamespaceLifecycle{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.Data = s.Data
	o.Namespace = s.Namespace
	o.NamespaceName = s.NamespaceName
	o.Revision = s.Revision
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *NamespaceLifecycle) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *NamespaceLifecycle) BleveType() string {

	return "namespacelifecycle"
}

// DefaultOrder returns the list of default ordering fields.
func (o *NamespaceLifecycle) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *NamespaceLifecycle) Doc() string {

	return `Private non-expiring namespace lifecycle coordination. This model has no public
CRUD route. Its identifier binds the native namespace incarnation, not its name.`
}

func (o *NamespaceLifecycle) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetNamespace returns the Namespace of the receiver.
func (o *NamespaceLifecycle) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *NamespaceLifecycle) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetZHash returns the ZHash of the receiver.
func (o *NamespaceLifecycle) GetZHash() int {

	return o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the given value.
func (o *NamespaceLifecycle) SetZHash(zHash int) {

	o.ZHash = zHash
}

// GetZone returns the Zone of the receiver.
func (o *NamespaceLifecycle) GetZone() int {

	return o.Zone
}

// SetZone sets the property Zone of the receiver using the given value.
func (o *NamespaceLifecycle) SetZone(zone int) {

	o.Zone = zone
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *NamespaceLifecycle) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseNamespaceLifecycle{
			ID:            &o.ID,
			Data:          &o.Data,
			Namespace:     &o.Namespace,
			NamespaceName: &o.NamespaceName,
			Revision:      &o.Revision,
			ZHash:         &o.ZHash,
			Zone:          &o.Zone,
		}
	}

	sp := &SparseNamespaceLifecycle{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "data":
			sp.Data = &(o.Data)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "namespaceName":
			sp.NamespaceName = &(o.NamespaceName)
		case "revision":
			sp.Revision = &(o.Revision)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseNamespaceLifecycle to the object.
func (o *NamespaceLifecycle) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseNamespaceLifecycle)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.Data != nil {
		o.Data = *so.Data
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.NamespaceName != nil {
		o.NamespaceName = *so.NamespaceName
	}
	if so.Revision != nil {
		o.Revision = *so.Revision
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *NamespaceLifecycle) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *NamespaceLifecycle) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the NamespaceLifecycle.
func (o *NamespaceLifecycle) DeepCopy() *NamespaceLifecycle {

	if o == nil {
		return nil
	}

	out := &NamespaceLifecycle{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *NamespaceLifecycle.
func (o *NamespaceLifecycle) DeepCopyInto(out *NamespaceLifecycle) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy NamespaceLifecycle: %s", err))
	}

	*out = *target.(*NamespaceLifecycle)
}

// Validate valides the current information stored into the structure.
func (o *NamespaceLifecycle) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*NamespaceLifecycle) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := NamespaceLifecycleAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return NamespaceLifecycleLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*NamespaceLifecycle) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return NamespaceLifecycleAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *NamespaceLifecycle) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "data":
		return o.Data
	case "namespace":
		return o.Namespace
	case "namespaceName":
		return o.NamespaceName
	case "revision":
		return o.Revision
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// NamespaceLifecycleAttributesMap represents the map of attribute for NamespaceLifecycle.
var NamespaceLifecycleAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Data": {
		AllowedChoices: []string{},
		BSONFieldName:  "data",
		ConvertedName:  "Data",
		Description:    `Bounded canonical lifecycle state owned by the namespace owner.`,
		Name:           "data",
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"NamespaceName": {
		AllowedChoices: []string{},
		BSONFieldName:  "namespacename",
		ConvertedName:  "NamespaceName",
		Description:    `Immutable canonical name retained across deletion to forbid unsafe reuse.`,
		Name:           "namespaceName",
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Revision": {
		AllowedChoices: []string{},
		BSONFieldName:  "revision",
		ConvertedName:  "Revision",
		Description:    `Monotonic conditional-write revision.`,
		Name:           "revision",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"ZHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"Zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// NamespaceLifecycleLowerCaseAttributesMap represents the map of attribute for NamespaceLifecycle.
var NamespaceLifecycleLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"data": {
		AllowedChoices: []string{},
		BSONFieldName:  "data",
		ConvertedName:  "Data",
		Description:    `Bounded canonical lifecycle state owned by the namespace owner.`,
		Name:           "data",
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"namespacename": {
		AllowedChoices: []string{},
		BSONFieldName:  "namespacename",
		ConvertedName:  "NamespaceName",
		Description:    `Immutable canonical name retained across deletion to forbid unsafe reuse.`,
		Name:           "namespaceName",
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"revision": {
		AllowedChoices: []string{},
		BSONFieldName:  "revision",
		ConvertedName:  "Revision",
		Description:    `Monotonic conditional-write revision.`,
		Name:           "revision",
		ReadOnly:       true,
		Stored:         true,
		Type:           "integer",
	},
	"zhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// SparseNamespaceLifecyclesList represents a list of SparseNamespaceLifecycles
type SparseNamespaceLifecyclesList []*SparseNamespaceLifecycle

// Identity returns the identity of the objects in the list.
func (o SparseNamespaceLifecyclesList) Identity() elemental.Identity {

	return NamespaceLifecycleIdentity
}

// Copy returns a pointer to a copy the SparseNamespaceLifecyclesList.
func (o SparseNamespaceLifecyclesList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseNamespaceLifecyclesList.
func (o SparseNamespaceLifecyclesList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseNamespaceLifecycle))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseNamespaceLifecyclesList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseNamespaceLifecyclesList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseNamespaceLifecyclesList converted to NamespaceLifecyclesList.
func (o SparseNamespaceLifecyclesList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseNamespaceLifecyclesList) Version() int {

	return 1
}

// SparseNamespaceLifecycle represents the sparse version of a namespacelifecycle.
type SparseNamespaceLifecycle struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Bounded canonical lifecycle state owned by the namespace owner.
	Data *string `json:"-" msgpack:"-" bson:"data,omitempty" mapstructure:"-,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Immutable canonical name retained across deletion to forbid unsafe reuse.
	NamespaceName *string `json:"-" msgpack:"-" bson:"namespacename,omitempty" mapstructure:"-,omitempty"`

	// Monotonic conditional-write revision.
	Revision *int `json:"-" msgpack:"-" bson:"revision,omitempty" mapstructure:"-,omitempty"`

	// Hash of the object used to shard the data.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseNamespaceLifecycle returns a new  SparseNamespaceLifecycle.
func NewSparseNamespaceLifecycle() *SparseNamespaceLifecycle {
	return &SparseNamespaceLifecycle{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseNamespaceLifecycle) Identity() elemental.Identity {

	return NamespaceLifecycleIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseNamespaceLifecycle) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseNamespaceLifecycle) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseNamespaceLifecycle) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseNamespaceLifecycle{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.Data != nil {
		s.Data = o.Data
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.NamespaceName != nil {
		s.NamespaceName = o.NamespaceName
	}
	if o.Revision != nil {
		s.Revision = o.Revision
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseNamespaceLifecycle) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseNamespaceLifecycle{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.Data != nil {
		o.Data = s.Data
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.NamespaceName != nil {
		o.NamespaceName = s.NamespaceName
	}
	if s.Revision != nil {
		o.Revision = s.Revision
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseNamespaceLifecycle) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseNamespaceLifecycle) ToPlain() elemental.PlainIdentifiable {

	out := NewNamespaceLifecycle()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.Data != nil {
		out.Data = *o.Data
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.NamespaceName != nil {
		out.NamespaceName = *o.NamespaceName
	}
	if o.Revision != nil {
		out.Revision = *o.Revision
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseNamespaceLifecycle) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseNamespaceLifecycle) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseNamespaceLifecycle) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseNamespaceLifecycle) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetZHash returns the ZHash of the receiver.
func (o *SparseNamespaceLifecycle) GetZHash() (out int) {

	if o.ZHash == nil {
		return
	}

	return *o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the address of the given value.
func (o *SparseNamespaceLifecycle) SetZHash(zHash int) {

	o.ZHash = &zHash
}

// GetZone returns the Zone of the receiver.
func (o *SparseNamespaceLifecycle) GetZone() (out int) {

	if o.Zone == nil {
		return
	}

	return *o.Zone
}

// SetZone sets the property Zone of the receiver using the address of the given value.
func (o *SparseNamespaceLifecycle) SetZone(zone int) {

	o.Zone = &zone
}

// DeepCopy returns a deep copy if the SparseNamespaceLifecycle.
func (o *SparseNamespaceLifecycle) DeepCopy() *SparseNamespaceLifecycle {

	if o == nil {
		return nil
	}

	out := &SparseNamespaceLifecycle{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseNamespaceLifecycle.
func (o *SparseNamespaceLifecycle) DeepCopyInto(out *SparseNamespaceLifecycle) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseNamespaceLifecycle: %s", err))
	}

	*out = *target.(*SparseNamespaceLifecycle)
}

type mongoAttributesNamespaceLifecycle struct {
	ID            bson.ObjectId `bson:"_id,omitempty"`
	Data          string        `bson:"data"`
	Namespace     string        `bson:"namespace,omitempty"`
	NamespaceName string        `bson:"namespacename"`
	Revision      int           `bson:"revision"`
	ZHash         int           `bson:"zhash"`
	Zone          int           `bson:"zone"`
}
type mongoAttributesSparseNamespaceLifecycle struct {
	ID            bson.ObjectId `bson:"_id,omitempty"`
	Data          *string       `bson:"data,omitempty"`
	Namespace     *string       `bson:"namespace,omitempty"`
	NamespaceName *string       `bson:"namespacename,omitempty"`
	Revision      *int          `bson:"revision,omitempty"`
	ZHash         *int          `bson:"zhash,omitempty"`
	Zone          *int          `bson:"zone,omitempty"`
}
