// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// NamespaceParticipationActionValue represents the possible values for attribute "action".
type NamespaceParticipationActionValue string

const (
	// NamespaceParticipationActionCaptureScope represents the value CaptureScope.
	NamespaceParticipationActionCaptureScope NamespaceParticipationActionValue = "CaptureScope"

	// NamespaceParticipationActionClaimEnrollment represents the value ClaimEnrollment.
	NamespaceParticipationActionClaimEnrollment NamespaceParticipationActionValue = "ClaimEnrollment"

	// NamespaceParticipationActionInspect represents the value Inspect.
	NamespaceParticipationActionInspect NamespaceParticipationActionValue = "Inspect"

	// NamespaceParticipationActionInspectDeletion represents the value InspectDeletion.
	NamespaceParticipationActionInspectDeletion NamespaceParticipationActionValue = "InspectDeletion"
)

// NamespaceParticipationIdentity represents the Identity of the object.
var NamespaceParticipationIdentity = elemental.Identity{
	Name:     "namespaceparticipation",
	Category: "namespaceparticipations",
	Package:  "a3s",
	Private:  false,
}

// NamespaceParticipationsList represents a list of NamespaceParticipations
type NamespaceParticipationsList []*NamespaceParticipation

// Identity returns the identity of the objects in the list.
func (o NamespaceParticipationsList) Identity() elemental.Identity {

	return NamespaceParticipationIdentity
}

// Copy returns a pointer to a copy the NamespaceParticipationsList.
func (o NamespaceParticipationsList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the NamespaceParticipationsList.
func (o NamespaceParticipationsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*NamespaceParticipation))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o NamespaceParticipationsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o NamespaceParticipationsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the NamespaceParticipationsList converted to SparseNamespaceParticipationsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o NamespaceParticipationsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseNamespaceParticipationsList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseNamespaceParticipation)
	}

	return out
}

// Version returns the version of the content.
func (o NamespaceParticipationsList) Version() int {

	return 1
}

// NamespaceParticipation represents the model of a namespaceparticipation
type NamespaceParticipation struct {
	// Inspect retained metadata, claim enrollment, or capture current owner scope without writer authority.
	Action NamespaceParticipationActionValue `json:"action" msgpack:"action" bson:"-" mapstructure:"action,omitempty"`

	// Exact retained deletion intent for InspectDeletion only.
	DeletionIntentID string `json:"deletionIntentID,omitempty" msgpack:"deletionIntentID,omitempty" bson:"-" mapstructure:"deletionIntentID,omitempty"`

	// True only for an acknowledged live attempted-to-claimed CAS.
	Granted bool `json:"granted" msgpack:"granted" bson:"-" mapstructure:"granted,omitempty"`

	// Exact native namespace incarnation. Required except for CaptureScope, which forbids this field.
	NamespaceID string `json:"namespaceID,omitempty" msgpack:"namespaceID,omitempty" bson:"-" mapstructure:"namespaceID,omitempty"`

	// Exact source-owned creation operation. Required except for CaptureScope, which forbids this field.
	OperationID string `json:"operationID,omitempty" msgpack:"operationID,omitempty" bson:"-" mapstructure:"operationID,omitempty"`

	// Trusted participant identifier, currently hanni.
	Participant string `json:"participant" msgpack:"participant" bson:"-" mapstructure:"participant,omitempty"`

	// Exact participant registry ID, equal to namespaceID. Required except for CaptureScope, which forbids this field.
	RegistryID string `json:"registryID,omitempty" msgpack:"registryID,omitempty" bson:"-" mapstructure:"registryID,omitempty"`

	// Validated source-owned namespace-enrollment.v1 metadata, never caller authority.
	Snapshot map[string]any `json:"snapshot" msgpack:"snapshot" bson:"-" mapstructure:"snapshot,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewNamespaceParticipation returns a new *NamespaceParticipation
func NewNamespaceParticipation() *NamespaceParticipation {

	return &NamespaceParticipation{
		ModelVersion: 1,
		Snapshot:     map[string]any{},
	}
}

// Identity returns the Identity of the object.
func (o *NamespaceParticipation) Identity() elemental.Identity {

	return NamespaceParticipationIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *NamespaceParticipation) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *NamespaceParticipation) SetIdentifier(id string) {

}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *NamespaceParticipation) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesNamespaceParticipation{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *NamespaceParticipation) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesNamespaceParticipation{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *NamespaceParticipation) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *NamespaceParticipation) BleveType() string {

	return "namespaceparticipation"
}

// DefaultOrder returns the list of default ordering fields.
func (o *NamespaceParticipation) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *NamespaceParticipation) Doc() string {

	return `Explicit development-only namespace enrollment command. No normal processor
registration enables this resource. All actions require current Create permission.`
}

func (o *NamespaceParticipation) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *NamespaceParticipation) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseNamespaceParticipation{
			Action:           &o.Action,
			DeletionIntentID: &o.DeletionIntentID,
			Granted:          &o.Granted,
			NamespaceID:      &o.NamespaceID,
			OperationID:      &o.OperationID,
			Participant:      &o.Participant,
			RegistryID:       &o.RegistryID,
			Snapshot:         &o.Snapshot,
		}
	}

	sp := &SparseNamespaceParticipation{}
	for _, f := range fields {
		switch f {
		case "action":
			sp.Action = &(o.Action)
		case "deletionIntentID":
			sp.DeletionIntentID = &(o.DeletionIntentID)
		case "granted":
			sp.Granted = &(o.Granted)
		case "namespaceID":
			sp.NamespaceID = &(o.NamespaceID)
		case "operationID":
			sp.OperationID = &(o.OperationID)
		case "participant":
			sp.Participant = &(o.Participant)
		case "registryID":
			sp.RegistryID = &(o.RegistryID)
		case "snapshot":
			sp.Snapshot = &(o.Snapshot)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseNamespaceParticipation to the object.
func (o *NamespaceParticipation) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseNamespaceParticipation)
	if so.Action != nil {
		o.Action = *so.Action
	}
	if so.DeletionIntentID != nil {
		o.DeletionIntentID = *so.DeletionIntentID
	}
	if so.Granted != nil {
		o.Granted = *so.Granted
	}
	if so.NamespaceID != nil {
		o.NamespaceID = *so.NamespaceID
	}
	if so.OperationID != nil {
		o.OperationID = *so.OperationID
	}
	if so.Participant != nil {
		o.Participant = *so.Participant
	}
	if so.RegistryID != nil {
		o.RegistryID = *so.RegistryID
	}
	if so.Snapshot != nil {
		o.Snapshot = *so.Snapshot
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *NamespaceParticipation) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *NamespaceParticipation) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the NamespaceParticipation.
func (o *NamespaceParticipation) DeepCopy() *NamespaceParticipation {

	if o == nil {
		return nil
	}

	out := &NamespaceParticipation{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *NamespaceParticipation.
func (o *NamespaceParticipation) DeepCopyInto(out *NamespaceParticipation) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy NamespaceParticipation: %s", err))
	}

	*out = *target.(*NamespaceParticipation)
}

// Validate valides the current information stored into the structure.
func (o *NamespaceParticipation) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("action", string(o.Action)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("action", string(o.Action), []string{"Inspect", "ClaimEnrollment", "InspectDeletion", "CaptureScope"}, false); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("participant", o.Participant); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*NamespaceParticipation) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := NamespaceParticipationAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return NamespaceParticipationLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*NamespaceParticipation) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return NamespaceParticipationAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *NamespaceParticipation) ValueForAttribute(name string) any {

	switch name {
	case "action":
		return o.Action
	case "deletionIntentID":
		return o.DeletionIntentID
	case "granted":
		return o.Granted
	case "namespaceID":
		return o.NamespaceID
	case "operationID":
		return o.OperationID
	case "participant":
		return o.Participant
	case "registryID":
		return o.RegistryID
	case "snapshot":
		return o.Snapshot
	}

	return nil
}

// NamespaceParticipationAttributesMap represents the map of attribute for NamespaceParticipation.
var NamespaceParticipationAttributesMap = map[string]elemental.AttributeSpecification{
	"Action": {
		AllowedChoices: []string{"Inspect", "ClaimEnrollment", "InspectDeletion", "CaptureScope"},
		ConvertedName:  "Action",
		Description:    `Inspect retained metadata, claim enrollment, or capture current owner scope without writer authority.`,
		Exposed:        true,
		Name:           "action",
		Required:       true,
		Type:           "enum",
	},
	"DeletionIntentID": {
		AllowedChoices: []string{},
		ConvertedName:  "DeletionIntentID",
		Description:    `Exact retained deletion intent for InspectDeletion only.`,
		Exposed:        true,
		Name:           "deletionIntentID",
		Type:           "string",
	},
	"Granted": {
		AllowedChoices: []string{},
		ConvertedName:  "Granted",
		Description:    `True only for an acknowledged live attempted-to-claimed CAS.`,
		Exposed:        true,
		Name:           "granted",
		ReadOnly:       true,
		Type:           "boolean",
	},
	"NamespaceID": {
		AllowedChoices: []string{},
		ConvertedName:  "NamespaceID",
		Description:    `Exact native namespace incarnation. Required except for CaptureScope, which forbids this field.`,
		Exposed:        true,
		Name:           "namespaceID",
		Type:           "string",
	},
	"OperationID": {
		AllowedChoices: []string{},
		ConvertedName:  "OperationID",
		Description:    `Exact source-owned creation operation. Required except for CaptureScope, which forbids this field.`,
		Exposed:        true,
		Name:           "operationID",
		Type:           "string",
	},
	"Participant": {
		AllowedChoices: []string{},
		ConvertedName:  "Participant",
		Description:    `Trusted participant identifier, currently hanni.`,
		Exposed:        true,
		Name:           "participant",
		Required:       true,
		Type:           "string",
	},
	"RegistryID": {
		AllowedChoices: []string{},
		ConvertedName:  "RegistryID",
		Description:    `Exact participant registry ID, equal to namespaceID. Required except for CaptureScope, which forbids this field.`,
		Exposed:        true,
		Name:           "registryID",
		Type:           "string",
	},
	"Snapshot": {
		AllowedChoices: []string{},
		ConvertedName:  "Snapshot",
		Description:    `Validated source-owned namespace-enrollment.v1 metadata, never caller authority.`,
		Exposed:        true,
		Name:           "snapshot",
		ReadOnly:       true,
		SubType:        "map[string]any",
		Type:           "external",
	},
}

// NamespaceParticipationLowerCaseAttributesMap represents the map of attribute for NamespaceParticipation.
var NamespaceParticipationLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"action": {
		AllowedChoices: []string{"Inspect", "ClaimEnrollment", "InspectDeletion", "CaptureScope"},
		ConvertedName:  "Action",
		Description:    `Inspect retained metadata, claim enrollment, or capture current owner scope without writer authority.`,
		Exposed:        true,
		Name:           "action",
		Required:       true,
		Type:           "enum",
	},
	"deletionintentid": {
		AllowedChoices: []string{},
		ConvertedName:  "DeletionIntentID",
		Description:    `Exact retained deletion intent for InspectDeletion only.`,
		Exposed:        true,
		Name:           "deletionIntentID",
		Type:           "string",
	},
	"granted": {
		AllowedChoices: []string{},
		ConvertedName:  "Granted",
		Description:    `True only for an acknowledged live attempted-to-claimed CAS.`,
		Exposed:        true,
		Name:           "granted",
		ReadOnly:       true,
		Type:           "boolean",
	},
	"namespaceid": {
		AllowedChoices: []string{},
		ConvertedName:  "NamespaceID",
		Description:    `Exact native namespace incarnation. Required except for CaptureScope, which forbids this field.`,
		Exposed:        true,
		Name:           "namespaceID",
		Type:           "string",
	},
	"operationid": {
		AllowedChoices: []string{},
		ConvertedName:  "OperationID",
		Description:    `Exact source-owned creation operation. Required except for CaptureScope, which forbids this field.`,
		Exposed:        true,
		Name:           "operationID",
		Type:           "string",
	},
	"participant": {
		AllowedChoices: []string{},
		ConvertedName:  "Participant",
		Description:    `Trusted participant identifier, currently hanni.`,
		Exposed:        true,
		Name:           "participant",
		Required:       true,
		Type:           "string",
	},
	"registryid": {
		AllowedChoices: []string{},
		ConvertedName:  "RegistryID",
		Description:    `Exact participant registry ID, equal to namespaceID. Required except for CaptureScope, which forbids this field.`,
		Exposed:        true,
		Name:           "registryID",
		Type:           "string",
	},
	"snapshot": {
		AllowedChoices: []string{},
		ConvertedName:  "Snapshot",
		Description:    `Validated source-owned namespace-enrollment.v1 metadata, never caller authority.`,
		Exposed:        true,
		Name:           "snapshot",
		ReadOnly:       true,
		SubType:        "map[string]any",
		Type:           "external",
	},
}

// SparseNamespaceParticipationsList represents a list of SparseNamespaceParticipations
type SparseNamespaceParticipationsList []*SparseNamespaceParticipation

// Identity returns the identity of the objects in the list.
func (o SparseNamespaceParticipationsList) Identity() elemental.Identity {

	return NamespaceParticipationIdentity
}

// Copy returns a pointer to a copy the SparseNamespaceParticipationsList.
func (o SparseNamespaceParticipationsList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseNamespaceParticipationsList.
func (o SparseNamespaceParticipationsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseNamespaceParticipation))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseNamespaceParticipationsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseNamespaceParticipationsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseNamespaceParticipationsList converted to NamespaceParticipationsList.
func (o SparseNamespaceParticipationsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseNamespaceParticipationsList) Version() int {

	return 1
}

// SparseNamespaceParticipation represents the sparse version of a namespaceparticipation.
type SparseNamespaceParticipation struct {
	// Inspect retained metadata, claim enrollment, or capture current owner scope without writer authority.
	Action *NamespaceParticipationActionValue `json:"action,omitempty" msgpack:"action,omitempty" bson:"-" mapstructure:"action,omitempty"`

	// Exact retained deletion intent for InspectDeletion only.
	DeletionIntentID *string `json:"deletionIntentID,omitempty" msgpack:"deletionIntentID,omitempty" bson:"-" mapstructure:"deletionIntentID,omitempty"`

	// True only for an acknowledged live attempted-to-claimed CAS.
	Granted *bool `json:"granted,omitempty" msgpack:"granted,omitempty" bson:"-" mapstructure:"granted,omitempty"`

	// Exact native namespace incarnation. Required except for CaptureScope, which forbids this field.
	NamespaceID *string `json:"namespaceID,omitempty" msgpack:"namespaceID,omitempty" bson:"-" mapstructure:"namespaceID,omitempty"`

	// Exact source-owned creation operation. Required except for CaptureScope, which forbids this field.
	OperationID *string `json:"operationID,omitempty" msgpack:"operationID,omitempty" bson:"-" mapstructure:"operationID,omitempty"`

	// Trusted participant identifier, currently hanni.
	Participant *string `json:"participant,omitempty" msgpack:"participant,omitempty" bson:"-" mapstructure:"participant,omitempty"`

	// Exact participant registry ID, equal to namespaceID. Required except for CaptureScope, which forbids this field.
	RegistryID *string `json:"registryID,omitempty" msgpack:"registryID,omitempty" bson:"-" mapstructure:"registryID,omitempty"`

	// Validated source-owned namespace-enrollment.v1 metadata, never caller authority.
	Snapshot *map[string]any `json:"snapshot,omitempty" msgpack:"snapshot,omitempty" bson:"-" mapstructure:"snapshot,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseNamespaceParticipation returns a new  SparseNamespaceParticipation.
func NewSparseNamespaceParticipation() *SparseNamespaceParticipation {
	return &SparseNamespaceParticipation{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseNamespaceParticipation) Identity() elemental.Identity {

	return NamespaceParticipationIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseNamespaceParticipation) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseNamespaceParticipation) SetIdentifier(id string) {

}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseNamespaceParticipation) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseNamespaceParticipation{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseNamespaceParticipation) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseNamespaceParticipation{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseNamespaceParticipation) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseNamespaceParticipation) ToPlain() elemental.PlainIdentifiable {

	out := NewNamespaceParticipation()
	if o.Action != nil {
		out.Action = *o.Action
	}
	if o.DeletionIntentID != nil {
		out.DeletionIntentID = *o.DeletionIntentID
	}
	if o.Granted != nil {
		out.Granted = *o.Granted
	}
	if o.NamespaceID != nil {
		out.NamespaceID = *o.NamespaceID
	}
	if o.OperationID != nil {
		out.OperationID = *o.OperationID
	}
	if o.Participant != nil {
		out.Participant = *o.Participant
	}
	if o.RegistryID != nil {
		out.RegistryID = *o.RegistryID
	}
	if o.Snapshot != nil {
		out.Snapshot = *o.Snapshot
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseNamespaceParticipation) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseNamespaceParticipation) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the SparseNamespaceParticipation.
func (o *SparseNamespaceParticipation) DeepCopy() *SparseNamespaceParticipation {

	if o == nil {
		return nil
	}

	out := &SparseNamespaceParticipation{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseNamespaceParticipation.
func (o *SparseNamespaceParticipation) DeepCopyInto(out *SparseNamespaceParticipation) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseNamespaceParticipation: %s", err))
	}

	*out = *target.(*SparseNamespaceParticipation)
}

type mongoAttributesNamespaceParticipation struct {
}
type mongoAttributesSparseNamespaceParticipation struct {
}
