// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// OAuthApplicationIdentity represents the Identity of the object.
var OAuthApplicationIdentity = elemental.Identity{
	Name:     "oauthapplication",
	Category: "oauthapplications",
	Package:  "a3s",
	Private:  false,
}

// OAuthApplicationsList represents a list of OAuthApplications
type OAuthApplicationsList []*OAuthApplication

// Identity returns the identity of the objects in the list.
func (o OAuthApplicationsList) Identity() elemental.Identity {

	return OAuthApplicationIdentity
}

// Copy returns a pointer to a copy the OAuthApplicationsList.
func (o OAuthApplicationsList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the OAuthApplicationsList.
func (o OAuthApplicationsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*OAuthApplication))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o OAuthApplicationsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o OAuthApplicationsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the OAuthApplicationsList converted to SparseOAuthApplicationsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o OAuthApplicationsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseOAuthApplicationsList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseOAuthApplication)
	}

	return out
}

// Version returns the version of the content.
func (o OAuthApplicationsList) Version() int {

	return 1
}

// OAuthApplication represents the model of a oauthapplication
type OAuthApplication struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Optional list of allowed interactive authentication sources. If omitted or
	// empty, any supported interactive source in the namespace is allowed. Each
	// entry is an Elemental filter expression evaluated against the resolved
	// source object, such as its `name` and `namespace`.
	AllowedSources []string `json:"allowedSources" msgpack:"allowedSources" bson:"allowedsources" mapstructure:"allowedSources,omitempty"`

	// Audience to use for resulting a3s access tokens.
	Audience string `json:"audience" msgpack:"audience" bson:"audience" mapstructure:"audience,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" msgpack:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// Default scopes to use when a client does not request any scope.
	DefaultScopes []string `json:"defaultScopes" msgpack:"defaultScopes" bson:"defaultscopes" mapstructure:"defaultScopes,omitempty"`

	// The description of the object.
	Description string `json:"description" msgpack:"description" bson:"description" mapstructure:"description,omitempty"`

	// If false, the OAuth application cannot be used.
	Enabled bool `json:"enabled" msgpack:"enabled" bson:"enabled" mapstructure:"enabled,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The name of the OAuth application.
	Name string `json:"name" msgpack:"name" bson:"name" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Last update date of the object.
	UpdateTime time.Time `json:"updateTime" msgpack:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewOAuthApplication returns a new *OAuthApplication
func NewOAuthApplication() *OAuthApplication {

	return &OAuthApplication{
		ModelVersion:   1,
		AllowedSources: []string{},
		DefaultScopes:  []string{},
		Enabled:        true,
	}
}

// Identity returns the Identity of the object.
func (o *OAuthApplication) Identity() elemental.Identity {

	return OAuthApplicationIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *OAuthApplication) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *OAuthApplication) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *OAuthApplication) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesOAuthApplication{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.AllowedSources = o.AllowedSources
	s.Audience = o.Audience
	s.CreateTime = o.CreateTime
	s.DefaultScopes = o.DefaultScopes
	s.Description = o.Description
	s.Enabled = o.Enabled
	s.ImportHash = o.ImportHash
	s.ImportLabel = o.ImportLabel
	s.Name = o.Name
	s.Namespace = o.Namespace
	s.UpdateTime = o.UpdateTime
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *OAuthApplication) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesOAuthApplication{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.AllowedSources = s.AllowedSources
	o.Audience = s.Audience
	o.CreateTime = s.CreateTime
	o.DefaultScopes = s.DefaultScopes
	o.Description = s.Description
	o.Enabled = s.Enabled
	o.ImportHash = s.ImportHash
	o.ImportLabel = s.ImportLabel
	o.Name = s.Name
	o.Namespace = s.Namespace
	o.UpdateTime = s.UpdateTime
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *OAuthApplication) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *OAuthApplication) BleveType() string {

	return "oauthapplication"
}

// DefaultOrder returns the list of default ordering fields.
func (o *OAuthApplication) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *OAuthApplication) Doc() string {

	return `An OAuth Application defines namespace-scoped OAuth behavior and policy used
by client registrations.`
}

func (o *OAuthApplication) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *OAuthApplication) GetCreateTime() time.Time {

	return o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the given value.
func (o *OAuthApplication) SetCreateTime(createTime time.Time) {

	o.CreateTime = createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *OAuthApplication) GetImportHash() string {

	return o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the given value.
func (o *OAuthApplication) SetImportHash(importHash string) {

	o.ImportHash = importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *OAuthApplication) GetImportLabel() string {

	return o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the given value.
func (o *OAuthApplication) SetImportLabel(importLabel string) {

	o.ImportLabel = importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *OAuthApplication) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *OAuthApplication) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *OAuthApplication) GetUpdateTime() time.Time {

	return o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the given value.
func (o *OAuthApplication) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = updateTime
}

// GetZHash returns the ZHash of the receiver.
func (o *OAuthApplication) GetZHash() int {

	return o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the given value.
func (o *OAuthApplication) SetZHash(zHash int) {

	o.ZHash = zHash
}

// GetZone returns the Zone of the receiver.
func (o *OAuthApplication) GetZone() int {

	return o.Zone
}

// SetZone sets the property Zone of the receiver using the given value.
func (o *OAuthApplication) SetZone(zone int) {

	o.Zone = zone
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *OAuthApplication) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseOAuthApplication{
			ID:             &o.ID,
			AllowedSources: &o.AllowedSources,
			Audience:       &o.Audience,
			CreateTime:     &o.CreateTime,
			DefaultScopes:  &o.DefaultScopes,
			Description:    &o.Description,
			Enabled:        &o.Enabled,
			ImportHash:     &o.ImportHash,
			ImportLabel:    &o.ImportLabel,
			Name:           &o.Name,
			Namespace:      &o.Namespace,
			UpdateTime:     &o.UpdateTime,
			ZHash:          &o.ZHash,
			Zone:           &o.Zone,
		}
	}

	sp := &SparseOAuthApplication{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "allowedSources":
			sp.AllowedSources = &(o.AllowedSources)
		case "audience":
			sp.Audience = &(o.Audience)
		case "createTime":
			sp.CreateTime = &(o.CreateTime)
		case "defaultScopes":
			sp.DefaultScopes = &(o.DefaultScopes)
		case "description":
			sp.Description = &(o.Description)
		case "enabled":
			sp.Enabled = &(o.Enabled)
		case "importHash":
			sp.ImportHash = &(o.ImportHash)
		case "importLabel":
			sp.ImportLabel = &(o.ImportLabel)
		case "name":
			sp.Name = &(o.Name)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "updateTime":
			sp.UpdateTime = &(o.UpdateTime)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseOAuthApplication to the object.
func (o *OAuthApplication) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseOAuthApplication)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.AllowedSources != nil {
		o.AllowedSources = *so.AllowedSources
	}
	if so.Audience != nil {
		o.Audience = *so.Audience
	}
	if so.CreateTime != nil {
		o.CreateTime = *so.CreateTime
	}
	if so.DefaultScopes != nil {
		o.DefaultScopes = *so.DefaultScopes
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.Enabled != nil {
		o.Enabled = *so.Enabled
	}
	if so.ImportHash != nil {
		o.ImportHash = *so.ImportHash
	}
	if so.ImportLabel != nil {
		o.ImportLabel = *so.ImportLabel
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.UpdateTime != nil {
		o.UpdateTime = *so.UpdateTime
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *OAuthApplication) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *OAuthApplication) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the OAuthApplication.
func (o *OAuthApplication) DeepCopy() *OAuthApplication {

	if o == nil {
		return nil
	}

	out := &OAuthApplication{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *OAuthApplication.
func (o *OAuthApplication) DeepCopyInto(out *OAuthApplication) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy OAuthApplication: %s", err))
	}

	*out = *target.(*OAuthApplication)
}

// Validate valides the current information stored into the structure.
func (o *OAuthApplication) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("audience", o.Audience); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*OAuthApplication) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := OAuthApplicationAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return OAuthApplicationLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*OAuthApplication) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return OAuthApplicationAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *OAuthApplication) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "allowedSources":
		return o.AllowedSources
	case "audience":
		return o.Audience
	case "createTime":
		return o.CreateTime
	case "defaultScopes":
		return o.DefaultScopes
	case "description":
		return o.Description
	case "enabled":
		return o.Enabled
	case "importHash":
		return o.ImportHash
	case "importLabel":
		return o.ImportLabel
	case "name":
		return o.Name
	case "namespace":
		return o.Namespace
	case "updateTime":
		return o.UpdateTime
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// OAuthApplicationAttributesMap represents the map of attribute for OAuthApplication.
var OAuthApplicationAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"AllowedSources": {
		AllowedChoices: []string{},
		BSONFieldName:  "allowedsources",
		ConvertedName:  "AllowedSources",
		Description: `Optional list of allowed interactive authentication sources. If omitted or
empty, any supported interactive source in the namespace is allowed. Each
entry is an Elemental filter expression evaluated against the resolved
source object, such as its ` + "`" + `name` + "`" + ` and ` + "`" + `namespace` + "`" + `.`,
		Exposed: true,
		Name:    "allowedSources",
		Stored:  true,
		SubType: "string",
		Type:    "list",
	},
	"Audience": {
		AllowedChoices: []string{},
		BSONFieldName:  "audience",
		ConvertedName:  "Audience",
		Description:    `Audience to use for resulting a3s access tokens.`,
		Exposed:        true,
		Name:           "audience",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"CreateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"DefaultScopes": {
		AllowedChoices: []string{},
		BSONFieldName:  "defaultscopes",
		ConvertedName:  "DefaultScopes",
		Description:    `Default scopes to use when a client does not request any scope.`,
		Exposed:        true,
		Name:           "defaultScopes",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the object.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"Enabled": {
		AllowedChoices: []string{},
		BSONFieldName:  "enabled",
		ConvertedName:  "Enabled",
		DefaultValue:   true,
		Description:    `If false, the OAuth application cannot be used.`,
		Exposed:        true,
		Name:           "enabled",
		Stored:         true,
		Type:           "boolean",
	},
	"ImportHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ImportLabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the OAuth application.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"UpdateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"ZHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"Zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// OAuthApplicationLowerCaseAttributesMap represents the map of attribute for OAuthApplication.
var OAuthApplicationLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"allowedsources": {
		AllowedChoices: []string{},
		BSONFieldName:  "allowedsources",
		ConvertedName:  "AllowedSources",
		Description: `Optional list of allowed interactive authentication sources. If omitted or
empty, any supported interactive source in the namespace is allowed. Each
entry is an Elemental filter expression evaluated against the resolved
source object, such as its ` + "`" + `name` + "`" + ` and ` + "`" + `namespace` + "`" + `.`,
		Exposed: true,
		Name:    "allowedSources",
		Stored:  true,
		SubType: "string",
		Type:    "list",
	},
	"audience": {
		AllowedChoices: []string{},
		BSONFieldName:  "audience",
		ConvertedName:  "Audience",
		Description:    `Audience to use for resulting a3s access tokens.`,
		Exposed:        true,
		Name:           "audience",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"createtime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"defaultscopes": {
		AllowedChoices: []string{},
		BSONFieldName:  "defaultscopes",
		ConvertedName:  "DefaultScopes",
		Description:    `Default scopes to use when a client does not request any scope.`,
		Exposed:        true,
		Name:           "defaultScopes",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the object.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"enabled": {
		AllowedChoices: []string{},
		BSONFieldName:  "enabled",
		ConvertedName:  "Enabled",
		DefaultValue:   true,
		Description:    `If false, the OAuth application cannot be used.`,
		Exposed:        true,
		Name:           "enabled",
		Stored:         true,
		Type:           "boolean",
	},
	"importhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"importlabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the OAuth application.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"updatetime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"zhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// SparseOAuthApplicationsList represents a list of SparseOAuthApplications
type SparseOAuthApplicationsList []*SparseOAuthApplication

// Identity returns the identity of the objects in the list.
func (o SparseOAuthApplicationsList) Identity() elemental.Identity {

	return OAuthApplicationIdentity
}

// Copy returns a pointer to a copy the SparseOAuthApplicationsList.
func (o SparseOAuthApplicationsList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseOAuthApplicationsList.
func (o SparseOAuthApplicationsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseOAuthApplication))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseOAuthApplicationsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseOAuthApplicationsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseOAuthApplicationsList converted to OAuthApplicationsList.
func (o SparseOAuthApplicationsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseOAuthApplicationsList) Version() int {

	return 1
}

// SparseOAuthApplication represents the sparse version of a oauthapplication.
type SparseOAuthApplication struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Optional list of allowed interactive authentication sources. If omitted or
	// empty, any supported interactive source in the namespace is allowed. Each
	// entry is an Elemental filter expression evaluated against the resolved
	// source object, such as its `name` and `namespace`.
	AllowedSources *[]string `json:"allowedSources,omitempty" msgpack:"allowedSources,omitempty" bson:"allowedsources,omitempty" mapstructure:"allowedSources,omitempty"`

	// Audience to use for resulting a3s access tokens.
	Audience *string `json:"audience,omitempty" msgpack:"audience,omitempty" bson:"audience,omitempty" mapstructure:"audience,omitempty"`

	// Creation date of the object.
	CreateTime *time.Time `json:"createTime,omitempty" msgpack:"createTime,omitempty" bson:"createtime,omitempty" mapstructure:"createTime,omitempty"`

	// Default scopes to use when a client does not request any scope.
	DefaultScopes *[]string `json:"defaultScopes,omitempty" msgpack:"defaultScopes,omitempty" bson:"defaultscopes,omitempty" mapstructure:"defaultScopes,omitempty"`

	// The description of the object.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// If false, the OAuth application cannot be used.
	Enabled *bool `json:"enabled,omitempty" msgpack:"enabled,omitempty" bson:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash *string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel *string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The name of the OAuth application.
	Name *string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Last update date of the object.
	UpdateTime *time.Time `json:"updateTime,omitempty" msgpack:"updateTime,omitempty" bson:"updatetime,omitempty" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseOAuthApplication returns a new  SparseOAuthApplication.
func NewSparseOAuthApplication() *SparseOAuthApplication {
	return &SparseOAuthApplication{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseOAuthApplication) Identity() elemental.Identity {

	return OAuthApplicationIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseOAuthApplication) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseOAuthApplication) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseOAuthApplication) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseOAuthApplication{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.AllowedSources != nil {
		s.AllowedSources = o.AllowedSources
	}
	if o.Audience != nil {
		s.Audience = o.Audience
	}
	if o.CreateTime != nil {
		s.CreateTime = o.CreateTime
	}
	if o.DefaultScopes != nil {
		s.DefaultScopes = o.DefaultScopes
	}
	if o.Description != nil {
		s.Description = o.Description
	}
	if o.Enabled != nil {
		s.Enabled = o.Enabled
	}
	if o.ImportHash != nil {
		s.ImportHash = o.ImportHash
	}
	if o.ImportLabel != nil {
		s.ImportLabel = o.ImportLabel
	}
	if o.Name != nil {
		s.Name = o.Name
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.UpdateTime != nil {
		s.UpdateTime = o.UpdateTime
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseOAuthApplication) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseOAuthApplication{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.AllowedSources != nil {
		o.AllowedSources = s.AllowedSources
	}
	if s.Audience != nil {
		o.Audience = s.Audience
	}
	if s.CreateTime != nil {
		o.CreateTime = s.CreateTime
	}
	if s.DefaultScopes != nil {
		o.DefaultScopes = s.DefaultScopes
	}
	if s.Description != nil {
		o.Description = s.Description
	}
	if s.Enabled != nil {
		o.Enabled = s.Enabled
	}
	if s.ImportHash != nil {
		o.ImportHash = s.ImportHash
	}
	if s.ImportLabel != nil {
		o.ImportLabel = s.ImportLabel
	}
	if s.Name != nil {
		o.Name = s.Name
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.UpdateTime != nil {
		o.UpdateTime = s.UpdateTime
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseOAuthApplication) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseOAuthApplication) ToPlain() elemental.PlainIdentifiable {

	out := NewOAuthApplication()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.AllowedSources != nil {
		out.AllowedSources = *o.AllowedSources
	}
	if o.Audience != nil {
		out.Audience = *o.Audience
	}
	if o.CreateTime != nil {
		out.CreateTime = *o.CreateTime
	}
	if o.DefaultScopes != nil {
		out.DefaultScopes = *o.DefaultScopes
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.Enabled != nil {
		out.Enabled = *o.Enabled
	}
	if o.ImportHash != nil {
		out.ImportHash = *o.ImportHash
	}
	if o.ImportLabel != nil {
		out.ImportLabel = *o.ImportLabel
	}
	if o.Name != nil {
		out.Name = *o.Name
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.UpdateTime != nil {
		out.UpdateTime = *o.UpdateTime
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseOAuthApplication) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseOAuthApplication) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *SparseOAuthApplication) GetCreateTime() (out time.Time) {

	if o.CreateTime == nil {
		return
	}

	return *o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetCreateTime(createTime time.Time) {

	o.CreateTime = &createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *SparseOAuthApplication) GetImportHash() (out string) {

	if o.ImportHash == nil {
		return
	}

	return *o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetImportHash(importHash string) {

	o.ImportHash = &importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *SparseOAuthApplication) GetImportLabel() (out string) {

	if o.ImportLabel == nil {
		return
	}

	return *o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetImportLabel(importLabel string) {

	o.ImportLabel = &importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseOAuthApplication) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *SparseOAuthApplication) GetUpdateTime() (out time.Time) {

	if o.UpdateTime == nil {
		return
	}

	return *o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = &updateTime
}

// GetZHash returns the ZHash of the receiver.
func (o *SparseOAuthApplication) GetZHash() (out int) {

	if o.ZHash == nil {
		return
	}

	return *o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetZHash(zHash int) {

	o.ZHash = &zHash
}

// GetZone returns the Zone of the receiver.
func (o *SparseOAuthApplication) GetZone() (out int) {

	if o.Zone == nil {
		return
	}

	return *o.Zone
}

// SetZone sets the property Zone of the receiver using the address of the given value.
func (o *SparseOAuthApplication) SetZone(zone int) {

	o.Zone = &zone
}

// DeepCopy returns a deep copy if the SparseOAuthApplication.
func (o *SparseOAuthApplication) DeepCopy() *SparseOAuthApplication {

	if o == nil {
		return nil
	}

	out := &SparseOAuthApplication{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseOAuthApplication.
func (o *SparseOAuthApplication) DeepCopyInto(out *SparseOAuthApplication) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseOAuthApplication: %s", err))
	}

	*out = *target.(*SparseOAuthApplication)
}

type mongoAttributesOAuthApplication struct {
	ID             bson.ObjectId `bson:"_id,omitempty"`
	AllowedSources []string      `bson:"allowedsources"`
	Audience       string        `bson:"audience"`
	CreateTime     time.Time     `bson:"createtime"`
	DefaultScopes  []string      `bson:"defaultscopes"`
	Description    string        `bson:"description"`
	Enabled        bool          `bson:"enabled"`
	ImportHash     string        `bson:"importhash,omitempty"`
	ImportLabel    string        `bson:"importlabel,omitempty"`
	Name           string        `bson:"name"`
	Namespace      string        `bson:"namespace,omitempty"`
	UpdateTime     time.Time     `bson:"updatetime"`
	ZHash          int           `bson:"zhash"`
	Zone           int           `bson:"zone"`
}
type mongoAttributesSparseOAuthApplication struct {
	ID             bson.ObjectId `bson:"_id,omitempty"`
	AllowedSources *[]string     `bson:"allowedsources,omitempty"`
	Audience       *string       `bson:"audience,omitempty"`
	CreateTime     *time.Time    `bson:"createtime,omitempty"`
	DefaultScopes  *[]string     `bson:"defaultscopes,omitempty"`
	Description    *string       `bson:"description,omitempty"`
	Enabled        *bool         `bson:"enabled,omitempty"`
	ImportHash     *string       `bson:"importhash,omitempty"`
	ImportLabel    *string       `bson:"importlabel,omitempty"`
	Name           *string       `bson:"name,omitempty"`
	Namespace      *string       `bson:"namespace,omitempty"`
	UpdateTime     *time.Time    `bson:"updatetime,omitempty"`
	ZHash          *int          `bson:"zhash,omitempty"`
	Zone           *int          `bson:"zone,omitempty"`
}
