// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// OAuthClientTokenEndpointAuthMethodValue represents the possible values for attribute "tokenEndpointAuthMethod".
type OAuthClientTokenEndpointAuthMethodValue string

const (
	// OAuthClientTokenEndpointAuthMethodClientSecretBasic represents the value ClientSecretBasic.
	OAuthClientTokenEndpointAuthMethodClientSecretBasic OAuthClientTokenEndpointAuthMethodValue = "ClientSecretBasic"

	// OAuthClientTokenEndpointAuthMethodClientSecretPost represents the value ClientSecretPost.
	OAuthClientTokenEndpointAuthMethodClientSecretPost OAuthClientTokenEndpointAuthMethodValue = "ClientSecretPost"

	// OAuthClientTokenEndpointAuthMethodNone represents the value None.
	OAuthClientTokenEndpointAuthMethodNone OAuthClientTokenEndpointAuthMethodValue = "None"
)

// OAuthClientIdentity represents the Identity of the object.
var OAuthClientIdentity = elemental.Identity{
	Name:     "oauthclient",
	Category: "oauthclients",
	Package:  "a3s",
	Private:  false,
}

// OAuthClientsList represents a list of OAuthClients
type OAuthClientsList []*OAuthClient

// Identity returns the identity of the objects in the list.
func (o OAuthClientsList) Identity() elemental.Identity {

	return OAuthClientIdentity
}

// Copy returns a pointer to a copy the OAuthClientsList.
func (o OAuthClientsList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the OAuthClientsList.
func (o OAuthClientsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*OAuthClient))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o OAuthClientsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o OAuthClientsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the OAuthClientsList converted to SparseOAuthClientsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o OAuthClientsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseOAuthClientsList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseOAuthClient)
	}

	return out
}

// Version returns the version of the content.
func (o OAuthClientsList) Version() int {

	return 1
}

// OAuthClient represents the model of a oauthclient
type OAuthClient struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Client identifier used in OAuth requests.
	ClientID string `json:"clientID" msgpack:"clientID" bson:"clientid" mapstructure:"clientID,omitempty"`

	// Client secret associated with the client ID.
	ClientSecret string `json:"clientSecret" msgpack:"clientSecret" bson:"clientsecret" mapstructure:"clientSecret,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" msgpack:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// The description of the object.
	Description string `json:"description" msgpack:"description" bson:"description" mapstructure:"description,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Identifier of the referenced OAuth application.
	OauthApplicationID string `json:"oauthApplicationID" msgpack:"oauthApplicationID" bson:"oauthapplicationid" mapstructure:"oauthApplicationID,omitempty"`

	// Namespace of the referenced OAuth application.
	OauthApplicationNamespace string `json:"oauthApplicationNamespace" msgpack:"oauthApplicationNamespace" bson:"oauthapplicationnamespace" mapstructure:"oauthApplicationNamespace,omitempty"`

	// List of allowed redirect URIs for the client.
	RedirectURIs []string `json:"redirectURIs" msgpack:"redirectURIs" bson:"redirecturis" mapstructure:"redirectURIs,omitempty"`

	// Scopes allowed for the client.
	Scopes []string `json:"scopes" msgpack:"scopes" bson:"scopes" mapstructure:"scopes,omitempty"`

	// How the client authenticates to the token endpoint.
	TokenEndpointAuthMethod OAuthClientTokenEndpointAuthMethodValue `json:"tokenEndpointAuthMethod" msgpack:"tokenEndpointAuthMethod" bson:"tokenendpointauthmethod" mapstructure:"tokenEndpointAuthMethod,omitempty"`

	// Last update date of the object.
	UpdateTime time.Time `json:"updateTime" msgpack:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewOAuthClient returns a new *OAuthClient
func NewOAuthClient() *OAuthClient {

	return &OAuthClient{
		ModelVersion: 1,
		RedirectURIs: []string{},
		Scopes:       []string{},
	}
}

// Identity returns the Identity of the object.
func (o *OAuthClient) Identity() elemental.Identity {

	return OAuthClientIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *OAuthClient) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *OAuthClient) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *OAuthClient) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesOAuthClient{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.ClientID = o.ClientID
	s.ClientSecret = o.ClientSecret
	s.CreateTime = o.CreateTime
	s.Description = o.Description
	s.ImportHash = o.ImportHash
	s.ImportLabel = o.ImportLabel
	s.Namespace = o.Namespace
	s.OauthApplicationID = o.OauthApplicationID
	s.OauthApplicationNamespace = o.OauthApplicationNamespace
	s.RedirectURIs = o.RedirectURIs
	s.Scopes = o.Scopes
	s.TokenEndpointAuthMethod = o.TokenEndpointAuthMethod
	s.UpdateTime = o.UpdateTime
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *OAuthClient) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesOAuthClient{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.ClientID = s.ClientID
	o.ClientSecret = s.ClientSecret
	o.CreateTime = s.CreateTime
	o.Description = s.Description
	o.ImportHash = s.ImportHash
	o.ImportLabel = s.ImportLabel
	o.Namespace = s.Namespace
	o.OauthApplicationID = s.OauthApplicationID
	o.OauthApplicationNamespace = s.OauthApplicationNamespace
	o.RedirectURIs = s.RedirectURIs
	o.Scopes = s.Scopes
	o.TokenEndpointAuthMethod = s.TokenEndpointAuthMethod
	o.UpdateTime = s.UpdateTime
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *OAuthClient) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *OAuthClient) BleveType() string {

	return "oauthclient"
}

// DefaultOrder returns the list of default ordering fields.
func (o *OAuthClient) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *OAuthClient) Doc() string {

	return `An OAuth Client is a namespace-scoped client registration linked to an OAuth
application.`
}

func (o *OAuthClient) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *OAuthClient) GetCreateTime() time.Time {

	return o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the given value.
func (o *OAuthClient) SetCreateTime(createTime time.Time) {

	o.CreateTime = createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *OAuthClient) GetImportHash() string {

	return o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the given value.
func (o *OAuthClient) SetImportHash(importHash string) {

	o.ImportHash = importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *OAuthClient) GetImportLabel() string {

	return o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the given value.
func (o *OAuthClient) SetImportLabel(importLabel string) {

	o.ImportLabel = importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *OAuthClient) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *OAuthClient) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *OAuthClient) GetUpdateTime() time.Time {

	return o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the given value.
func (o *OAuthClient) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = updateTime
}

// GetZHash returns the ZHash of the receiver.
func (o *OAuthClient) GetZHash() int {

	return o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the given value.
func (o *OAuthClient) SetZHash(zHash int) {

	o.ZHash = zHash
}

// GetZone returns the Zone of the receiver.
func (o *OAuthClient) GetZone() int {

	return o.Zone
}

// SetZone sets the property Zone of the receiver using the given value.
func (o *OAuthClient) SetZone(zone int) {

	o.Zone = zone
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *OAuthClient) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseOAuthClient{
			ID:                        &o.ID,
			ClientID:                  &o.ClientID,
			ClientSecret:              &o.ClientSecret,
			CreateTime:                &o.CreateTime,
			Description:               &o.Description,
			ImportHash:                &o.ImportHash,
			ImportLabel:               &o.ImportLabel,
			Namespace:                 &o.Namespace,
			OauthApplicationID:        &o.OauthApplicationID,
			OauthApplicationNamespace: &o.OauthApplicationNamespace,
			RedirectURIs:              &o.RedirectURIs,
			Scopes:                    &o.Scopes,
			TokenEndpointAuthMethod:   &o.TokenEndpointAuthMethod,
			UpdateTime:                &o.UpdateTime,
			ZHash:                     &o.ZHash,
			Zone:                      &o.Zone,
		}
	}

	sp := &SparseOAuthClient{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "clientID":
			sp.ClientID = &(o.ClientID)
		case "clientSecret":
			sp.ClientSecret = &(o.ClientSecret)
		case "createTime":
			sp.CreateTime = &(o.CreateTime)
		case "description":
			sp.Description = &(o.Description)
		case "importHash":
			sp.ImportHash = &(o.ImportHash)
		case "importLabel":
			sp.ImportLabel = &(o.ImportLabel)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "oauthApplicationID":
			sp.OauthApplicationID = &(o.OauthApplicationID)
		case "oauthApplicationNamespace":
			sp.OauthApplicationNamespace = &(o.OauthApplicationNamespace)
		case "redirectURIs":
			sp.RedirectURIs = &(o.RedirectURIs)
		case "scopes":
			sp.Scopes = &(o.Scopes)
		case "tokenEndpointAuthMethod":
			sp.TokenEndpointAuthMethod = &(o.TokenEndpointAuthMethod)
		case "updateTime":
			sp.UpdateTime = &(o.UpdateTime)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseOAuthClient to the object.
func (o *OAuthClient) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseOAuthClient)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.ClientID != nil {
		o.ClientID = *so.ClientID
	}
	if so.ClientSecret != nil {
		o.ClientSecret = *so.ClientSecret
	}
	if so.CreateTime != nil {
		o.CreateTime = *so.CreateTime
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.ImportHash != nil {
		o.ImportHash = *so.ImportHash
	}
	if so.ImportLabel != nil {
		o.ImportLabel = *so.ImportLabel
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.OauthApplicationID != nil {
		o.OauthApplicationID = *so.OauthApplicationID
	}
	if so.OauthApplicationNamespace != nil {
		o.OauthApplicationNamespace = *so.OauthApplicationNamespace
	}
	if so.RedirectURIs != nil {
		o.RedirectURIs = *so.RedirectURIs
	}
	if so.Scopes != nil {
		o.Scopes = *so.Scopes
	}
	if so.TokenEndpointAuthMethod != nil {
		o.TokenEndpointAuthMethod = *so.TokenEndpointAuthMethod
	}
	if so.UpdateTime != nil {
		o.UpdateTime = *so.UpdateTime
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *OAuthClient) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.ClientSecret, err = encrypter.EncryptString(o.ClientSecret); err != nil {
		return fmt.Errorf("unable to encrypt attribute 'ClientSecret' for 'OAuthClient' (%s): %w", o.Identifier(), err)
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *OAuthClient) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.ClientSecret, err = encrypter.DecryptString(o.ClientSecret); err != nil {
		return fmt.Errorf("unable to decrypt attribute 'ClientSecret' for 'OAuthClient' (%s): %w", o.Identifier(), err)
	}

	return nil
}

// DeepCopy returns a deep copy if the OAuthClient.
func (o *OAuthClient) DeepCopy() *OAuthClient {

	if o == nil {
		return nil
	}

	out := &OAuthClient{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *OAuthClient.
func (o *OAuthClient) DeepCopyInto(out *OAuthClient) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy OAuthClient: %s", err))
	}

	*out = *target.(*OAuthClient)
}

// Validate valides the current information stored into the structure.
func (o *OAuthClient) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("clientID", o.ClientID); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("oauthApplicationID", o.OauthApplicationID); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("oauthApplicationNamespace", o.OauthApplicationNamespace); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredExternal("redirectURIs", o.RedirectURIs); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := ValidateURLList("redirectURIs", o.RedirectURIs); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("tokenEndpointAuthMethod", string(o.TokenEndpointAuthMethod)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("tokenEndpointAuthMethod", string(o.TokenEndpointAuthMethod), []string{"ClientSecretBasic", "ClientSecretPost", "None"}, false); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*OAuthClient) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := OAuthClientAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return OAuthClientLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*OAuthClient) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return OAuthClientAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *OAuthClient) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "clientID":
		return o.ClientID
	case "clientSecret":
		return o.ClientSecret
	case "createTime":
		return o.CreateTime
	case "description":
		return o.Description
	case "importHash":
		return o.ImportHash
	case "importLabel":
		return o.ImportLabel
	case "namespace":
		return o.Namespace
	case "oauthApplicationID":
		return o.OauthApplicationID
	case "oauthApplicationNamespace":
		return o.OauthApplicationNamespace
	case "redirectURIs":
		return o.RedirectURIs
	case "scopes":
		return o.Scopes
	case "tokenEndpointAuthMethod":
		return o.TokenEndpointAuthMethod
	case "updateTime":
		return o.UpdateTime
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// OAuthClientAttributesMap represents the map of attribute for OAuthClient.
var OAuthClientAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"ClientID": {
		AllowedChoices: []string{},
		BSONFieldName:  "clientid",
		ConvertedName:  "ClientID",
		Description:    `Client identifier used in OAuth requests.`,
		Exposed:        true,
		Name:           "clientID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"ClientSecret": {
		AllowedChoices: []string{},
		BSONFieldName:  "clientsecret",
		ConvertedName:  "ClientSecret",
		Description:    `Client secret associated with the client ID.`,
		Encrypted:      true,
		Exposed:        true,
		Name:           "clientSecret",
		Secret:         true,
		Stored:         true,
		Transient:      true,
		Type:           "string",
	},
	"CreateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the object.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"ImportHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ImportLabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"OauthApplicationID": {
		AllowedChoices: []string{},
		BSONFieldName:  "oauthapplicationid",
		ConvertedName:  "OauthApplicationID",
		Description:    `Identifier of the referenced OAuth application.`,
		Exposed:        true,
		Name:           "oauthApplicationID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"OauthApplicationNamespace": {
		AllowedChoices: []string{},
		BSONFieldName:  "oauthapplicationnamespace",
		ConvertedName:  "OauthApplicationNamespace",
		Description:    `Namespace of the referenced OAuth application.`,
		Exposed:        true,
		Name:           "oauthApplicationNamespace",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"RedirectURIs": {
		AllowedChoices: []string{},
		BSONFieldName:  "redirecturis",
		ConvertedName:  "RedirectURIs",
		Description:    `List of allowed redirect URIs for the client.`,
		Exposed:        true,
		Name:           "redirectURIs",
		Required:       true,
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"Scopes": {
		AllowedChoices: []string{},
		BSONFieldName:  "scopes",
		ConvertedName:  "Scopes",
		Description:    `Scopes allowed for the client.`,
		Exposed:        true,
		Name:           "scopes",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"TokenEndpointAuthMethod": {
		AllowedChoices: []string{"ClientSecretBasic", "ClientSecretPost", "None"},
		BSONFieldName:  "tokenendpointauthmethod",
		ConvertedName:  "TokenEndpointAuthMethod",
		Description:    `How the client authenticates to the token endpoint.`,
		Exposed:        true,
		Name:           "tokenEndpointAuthMethod",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"UpdateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"ZHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"Zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// OAuthClientLowerCaseAttributesMap represents the map of attribute for OAuthClient.
var OAuthClientLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"clientid": {
		AllowedChoices: []string{},
		BSONFieldName:  "clientid",
		ConvertedName:  "ClientID",
		Description:    `Client identifier used in OAuth requests.`,
		Exposed:        true,
		Name:           "clientID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"clientsecret": {
		AllowedChoices: []string{},
		BSONFieldName:  "clientsecret",
		ConvertedName:  "ClientSecret",
		Description:    `Client secret associated with the client ID.`,
		Encrypted:      true,
		Exposed:        true,
		Name:           "clientSecret",
		Secret:         true,
		Stored:         true,
		Transient:      true,
		Type:           "string",
	},
	"createtime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the object.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"importhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"importlabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"oauthapplicationid": {
		AllowedChoices: []string{},
		BSONFieldName:  "oauthapplicationid",
		ConvertedName:  "OauthApplicationID",
		Description:    `Identifier of the referenced OAuth application.`,
		Exposed:        true,
		Name:           "oauthApplicationID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"oauthapplicationnamespace": {
		AllowedChoices: []string{},
		BSONFieldName:  "oauthapplicationnamespace",
		ConvertedName:  "OauthApplicationNamespace",
		Description:    `Namespace of the referenced OAuth application.`,
		Exposed:        true,
		Name:           "oauthApplicationNamespace",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"redirecturis": {
		AllowedChoices: []string{},
		BSONFieldName:  "redirecturis",
		ConvertedName:  "RedirectURIs",
		Description:    `List of allowed redirect URIs for the client.`,
		Exposed:        true,
		Name:           "redirectURIs",
		Required:       true,
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"scopes": {
		AllowedChoices: []string{},
		BSONFieldName:  "scopes",
		ConvertedName:  "Scopes",
		Description:    `Scopes allowed for the client.`,
		Exposed:        true,
		Name:           "scopes",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"tokenendpointauthmethod": {
		AllowedChoices: []string{"ClientSecretBasic", "ClientSecretPost", "None"},
		BSONFieldName:  "tokenendpointauthmethod",
		ConvertedName:  "TokenEndpointAuthMethod",
		Description:    `How the client authenticates to the token endpoint.`,
		Exposed:        true,
		Name:           "tokenEndpointAuthMethod",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"updatetime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"zhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// SparseOAuthClientsList represents a list of SparseOAuthClients
type SparseOAuthClientsList []*SparseOAuthClient

// Identity returns the identity of the objects in the list.
func (o SparseOAuthClientsList) Identity() elemental.Identity {

	return OAuthClientIdentity
}

// Copy returns a pointer to a copy the SparseOAuthClientsList.
func (o SparseOAuthClientsList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseOAuthClientsList.
func (o SparseOAuthClientsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseOAuthClient))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseOAuthClientsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseOAuthClientsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseOAuthClientsList converted to OAuthClientsList.
func (o SparseOAuthClientsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseOAuthClientsList) Version() int {

	return 1
}

// SparseOAuthClient represents the sparse version of a oauthclient.
type SparseOAuthClient struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Client identifier used in OAuth requests.
	ClientID *string `json:"clientID,omitempty" msgpack:"clientID,omitempty" bson:"clientid,omitempty" mapstructure:"clientID,omitempty"`

	// Client secret associated with the client ID.
	ClientSecret *string `json:"clientSecret,omitempty" msgpack:"clientSecret,omitempty" bson:"clientsecret,omitempty" mapstructure:"clientSecret,omitempty"`

	// Creation date of the object.
	CreateTime *time.Time `json:"createTime,omitempty" msgpack:"createTime,omitempty" bson:"createtime,omitempty" mapstructure:"createTime,omitempty"`

	// The description of the object.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash *string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel *string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Identifier of the referenced OAuth application.
	OauthApplicationID *string `json:"oauthApplicationID,omitempty" msgpack:"oauthApplicationID,omitempty" bson:"oauthapplicationid,omitempty" mapstructure:"oauthApplicationID,omitempty"`

	// Namespace of the referenced OAuth application.
	OauthApplicationNamespace *string `json:"oauthApplicationNamespace,omitempty" msgpack:"oauthApplicationNamespace,omitempty" bson:"oauthapplicationnamespace,omitempty" mapstructure:"oauthApplicationNamespace,omitempty"`

	// List of allowed redirect URIs for the client.
	RedirectURIs *[]string `json:"redirectURIs,omitempty" msgpack:"redirectURIs,omitempty" bson:"redirecturis,omitempty" mapstructure:"redirectURIs,omitempty"`

	// Scopes allowed for the client.
	Scopes *[]string `json:"scopes,omitempty" msgpack:"scopes,omitempty" bson:"scopes,omitempty" mapstructure:"scopes,omitempty"`

	// How the client authenticates to the token endpoint.
	TokenEndpointAuthMethod *OAuthClientTokenEndpointAuthMethodValue `json:"tokenEndpointAuthMethod,omitempty" msgpack:"tokenEndpointAuthMethod,omitempty" bson:"tokenendpointauthmethod,omitempty" mapstructure:"tokenEndpointAuthMethod,omitempty"`

	// Last update date of the object.
	UpdateTime *time.Time `json:"updateTime,omitempty" msgpack:"updateTime,omitempty" bson:"updatetime,omitempty" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseOAuthClient returns a new  SparseOAuthClient.
func NewSparseOAuthClient() *SparseOAuthClient {
	return &SparseOAuthClient{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseOAuthClient) Identity() elemental.Identity {

	return OAuthClientIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseOAuthClient) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseOAuthClient) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseOAuthClient) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseOAuthClient{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.ClientID != nil {
		s.ClientID = o.ClientID
	}
	if o.ClientSecret != nil {
		s.ClientSecret = o.ClientSecret
	}
	if o.CreateTime != nil {
		s.CreateTime = o.CreateTime
	}
	if o.Description != nil {
		s.Description = o.Description
	}
	if o.ImportHash != nil {
		s.ImportHash = o.ImportHash
	}
	if o.ImportLabel != nil {
		s.ImportLabel = o.ImportLabel
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.OauthApplicationID != nil {
		s.OauthApplicationID = o.OauthApplicationID
	}
	if o.OauthApplicationNamespace != nil {
		s.OauthApplicationNamespace = o.OauthApplicationNamespace
	}
	if o.RedirectURIs != nil {
		s.RedirectURIs = o.RedirectURIs
	}
	if o.Scopes != nil {
		s.Scopes = o.Scopes
	}
	if o.TokenEndpointAuthMethod != nil {
		s.TokenEndpointAuthMethod = o.TokenEndpointAuthMethod
	}
	if o.UpdateTime != nil {
		s.UpdateTime = o.UpdateTime
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseOAuthClient) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseOAuthClient{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.ClientID != nil {
		o.ClientID = s.ClientID
	}
	if s.ClientSecret != nil {
		o.ClientSecret = s.ClientSecret
	}
	if s.CreateTime != nil {
		o.CreateTime = s.CreateTime
	}
	if s.Description != nil {
		o.Description = s.Description
	}
	if s.ImportHash != nil {
		o.ImportHash = s.ImportHash
	}
	if s.ImportLabel != nil {
		o.ImportLabel = s.ImportLabel
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.OauthApplicationID != nil {
		o.OauthApplicationID = s.OauthApplicationID
	}
	if s.OauthApplicationNamespace != nil {
		o.OauthApplicationNamespace = s.OauthApplicationNamespace
	}
	if s.RedirectURIs != nil {
		o.RedirectURIs = s.RedirectURIs
	}
	if s.Scopes != nil {
		o.Scopes = s.Scopes
	}
	if s.TokenEndpointAuthMethod != nil {
		o.TokenEndpointAuthMethod = s.TokenEndpointAuthMethod
	}
	if s.UpdateTime != nil {
		o.UpdateTime = s.UpdateTime
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseOAuthClient) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseOAuthClient) ToPlain() elemental.PlainIdentifiable {

	out := NewOAuthClient()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.ClientID != nil {
		out.ClientID = *o.ClientID
	}
	if o.ClientSecret != nil {
		out.ClientSecret = *o.ClientSecret
	}
	if o.CreateTime != nil {
		out.CreateTime = *o.CreateTime
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.ImportHash != nil {
		out.ImportHash = *o.ImportHash
	}
	if o.ImportLabel != nil {
		out.ImportLabel = *o.ImportLabel
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.OauthApplicationID != nil {
		out.OauthApplicationID = *o.OauthApplicationID
	}
	if o.OauthApplicationNamespace != nil {
		out.OauthApplicationNamespace = *o.OauthApplicationNamespace
	}
	if o.RedirectURIs != nil {
		out.RedirectURIs = *o.RedirectURIs
	}
	if o.Scopes != nil {
		out.Scopes = *o.Scopes
	}
	if o.TokenEndpointAuthMethod != nil {
		out.TokenEndpointAuthMethod = *o.TokenEndpointAuthMethod
	}
	if o.UpdateTime != nil {
		out.UpdateTime = *o.UpdateTime
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseOAuthClient) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if *o.ClientSecret, err = encrypter.EncryptString(*o.ClientSecret); err != nil {
		return fmt.Errorf("unable to encrypt attribute 'ClientSecret' for 'SparseOAuthClient' (%s): %w", o.Identifier(), err)
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseOAuthClient) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if *o.ClientSecret, err = encrypter.DecryptString(*o.ClientSecret); err != nil {
		return fmt.Errorf("unable to decrypt attribute 'ClientSecret' for 'SparseOAuthClient' (%s): %w", o.Identifier(), err)
	}

	return nil
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *SparseOAuthClient) GetCreateTime() (out time.Time) {

	if o.CreateTime == nil {
		return
	}

	return *o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetCreateTime(createTime time.Time) {

	o.CreateTime = &createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *SparseOAuthClient) GetImportHash() (out string) {

	if o.ImportHash == nil {
		return
	}

	return *o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetImportHash(importHash string) {

	o.ImportHash = &importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *SparseOAuthClient) GetImportLabel() (out string) {

	if o.ImportLabel == nil {
		return
	}

	return *o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetImportLabel(importLabel string) {

	o.ImportLabel = &importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseOAuthClient) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *SparseOAuthClient) GetUpdateTime() (out time.Time) {

	if o.UpdateTime == nil {
		return
	}

	return *o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = &updateTime
}

// GetZHash returns the ZHash of the receiver.
func (o *SparseOAuthClient) GetZHash() (out int) {

	if o.ZHash == nil {
		return
	}

	return *o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetZHash(zHash int) {

	o.ZHash = &zHash
}

// GetZone returns the Zone of the receiver.
func (o *SparseOAuthClient) GetZone() (out int) {

	if o.Zone == nil {
		return
	}

	return *o.Zone
}

// SetZone sets the property Zone of the receiver using the address of the given value.
func (o *SparseOAuthClient) SetZone(zone int) {

	o.Zone = &zone
}

// DeepCopy returns a deep copy if the SparseOAuthClient.
func (o *SparseOAuthClient) DeepCopy() *SparseOAuthClient {

	if o == nil {
		return nil
	}

	out := &SparseOAuthClient{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseOAuthClient.
func (o *SparseOAuthClient) DeepCopyInto(out *SparseOAuthClient) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseOAuthClient: %s", err))
	}

	*out = *target.(*SparseOAuthClient)
}

type mongoAttributesOAuthClient struct {
	ID                        bson.ObjectId                           `bson:"_id,omitempty"`
	ClientID                  string                                  `bson:"clientid"`
	ClientSecret              string                                  `bson:"clientsecret"`
	CreateTime                time.Time                               `bson:"createtime"`
	Description               string                                  `bson:"description"`
	ImportHash                string                                  `bson:"importhash,omitempty"`
	ImportLabel               string                                  `bson:"importlabel,omitempty"`
	Namespace                 string                                  `bson:"namespace,omitempty"`
	OauthApplicationID        string                                  `bson:"oauthapplicationid"`
	OauthApplicationNamespace string                                  `bson:"oauthapplicationnamespace"`
	RedirectURIs              []string                                `bson:"redirecturis"`
	Scopes                    []string                                `bson:"scopes"`
	TokenEndpointAuthMethod   OAuthClientTokenEndpointAuthMethodValue `bson:"tokenendpointauthmethod"`
	UpdateTime                time.Time                               `bson:"updatetime"`
	ZHash                     int                                     `bson:"zhash"`
	Zone                      int                                     `bson:"zone"`
}
type mongoAttributesSparseOAuthClient struct {
	ID                        bson.ObjectId                            `bson:"_id,omitempty"`
	ClientID                  *string                                  `bson:"clientid,omitempty"`
	ClientSecret              *string                                  `bson:"clientsecret,omitempty"`
	CreateTime                *time.Time                               `bson:"createtime,omitempty"`
	Description               *string                                  `bson:"description,omitempty"`
	ImportHash                *string                                  `bson:"importhash,omitempty"`
	ImportLabel               *string                                  `bson:"importlabel,omitempty"`
	Namespace                 *string                                  `bson:"namespace,omitempty"`
	OauthApplicationID        *string                                  `bson:"oauthapplicationid,omitempty"`
	OauthApplicationNamespace *string                                  `bson:"oauthapplicationnamespace,omitempty"`
	RedirectURIs              *[]string                                `bson:"redirecturis,omitempty"`
	Scopes                    *[]string                                `bson:"scopes,omitempty"`
	TokenEndpointAuthMethod   *OAuthClientTokenEndpointAuthMethodValue `bson:"tokenendpointauthmethod,omitempty"`
	UpdateTime                *time.Time                               `bson:"updatetime,omitempty"`
	ZHash                     *int                                     `bson:"zhash,omitempty"`
	Zone                      *int                                     `bson:"zone,omitempty"`
}
