# Model
model:
  rest_name: mtlssourceentra
  resource_name: mtlssourceentra
  entity_name: MTLSSourceEntra
  friendly_name: MTLS Source Entra
  package: a3s
  group: authn/issue
  description: |-
    Additional authentication information for MTLS source getting information from
    Entra.

    You will need to set clientTenantID, clientID and clientSecret.

    You will also need an Entra application that has the following permissions:
    Directory.Read.All and User.Read.
  detached: true

# Attributes
attributes:
  v1:
  - name: clientID
    friendly_name: Client ID
    description: |-
      The oauth clientID if any. This may be required for autologin, depending on the
      mode.
    type: string
    exposed: true
    stored: true
    example_value: a83e57d8-24af-4aec-bc8f-822db8d165b0
    omit_empty: true

  - name: clientSecret
    friendly_name: Client Secret
    description: |-
      Client secret associated with the client ID. This may be required for autologin,
      depending on the mode.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: Ytgbfjtj4652jHDFGls99jF
    secret: true
    transient: true
    encrypted: true

  - name: clientTenantID
    friendly_name: Client Tenant ID
    description: |-
      ID of the tenant for the identity provider, if any. This may be required for
      autologin, depending on the mode.
    type: string
    exposed: true
    stored: true
    example_value: a83e57d8-24af-4aec-bc8f-822db8d165b0
    omit_empty: true

  - name: entraAccessToken
    friendly_name: Entra Access Token
    description: Stores the latest Entra Access Token.
    type: string
    stored: true
    autogenerated: true
    transient: true
    omit_empty: true
    encrypted: true

  - name: graphEventSecret
    friendly_name: Graph Event Secret
    description: Holds the secret used to authentify the calls from Entra.
    type: string
    stored: true
    autogenerated: true
    transient: true
    omit_empty: true

  - name: graphEventsEnabled
    friendly_name: Enable Graph Events
    description: |-
      Enables background jobs to maintain subscriptions to Entra to be notified of
      changes in groups, users and memmber assignation. This requires A3S to be
      configured with an event hook endpoint.
    type: boolean
    exposed: true
    stored: true

  - name: graphSubscriptionExpiration
    friendly_name: Graph Subscription Expiration
    description: Holds when the subscription will expire.
    type: time
    stored: true
    autogenerated: true
    transient: true
    omit_empty: true

  - name: graphSubscriptionIDs
    friendly_name: Graph Subscription IDs
    description: Holds the last subscription IDs to try to renew them.
    type: external
    subtype: map[string]string
    stored: true
    autogenerated: true
    transient: true
    omit_empty: true
